# Generated by Django 4.0 on 2021-12-23 05:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('object_id', models.PositiveIntegerField()),
                ('value', models.FloatField()),
                ('content_type', models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'recommend'), ('model', 'dora_kpi')), models.Q(('app_label', 'recommend'), ('model', 'metric')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, related_name='measurement_content_type', to='contenttypes.contenttype')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_history', to='recommend.team')),
            ],
        ),
    ]
