# Generated by Django 4.0 on 2021-12-23 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dora_kpi',
            name='elite_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='high_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='max_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='medium_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='min_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='elite_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='high_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='max_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='medium_threshold_value',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='min_value',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='score',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Helpful')], null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_person',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
