# Generated by Django 4.0 on 2021-12-17 03:39

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_alter_recommendation_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='metric_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('measured_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('metric1', models.FloatField()),
                ('metric2', models.FloatField()),
                ('metric3', models.FloatField()),
                ('metric4', models.FloatField()),
                ('metric5', models.FloatField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metric_history', to='recommend.team')),
            ],
        ),
    ]
