# Generated by Django 4.0 on 2021-12-17 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0005_correlation_dora_kpi_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='dora_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.dora_kpi', unique=True),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.metric', unique=True),
        ),
    ]
