# Generated by Django 4.0 on 2021-12-17 05:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0006_alter_correlation_dora_kpi_alter_correlation_metric'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correlation',
            name='dora_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.dora_kpi'),
        ),
        migrations.AlterField(
            model_name='correlation',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.metric'),
        ),
    ]
