# Generated by Django 4.0 on 2021-12-17 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0007_alter_correlation_dora_kpi_alter_correlation_metric'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='correlation',
            unique_together={('dora_kpi', 'metric')},
        ),
    ]
