# Generated by Django 4.0 on 2021-12-27 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendation',
            name='metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='recommend.metric'),
        ),
    ]
