# Generated by Django 4.0 on 2021-12-23 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('recommend', '0002_measurement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dora_kpi',
            name='elite_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='high_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='max_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='medium_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='dora_kpi',
            name='min_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='measurement',
            name='content_type',
            field=models.ForeignKey(limit_choices_to=models.Q(models.Q(('app_label', 'recommend'), ('model', 'dora_kpi')), models.Q(('app_label', 'recommend'), ('model', 'metric')), _connector='OR'), on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AlterField(
            model_name='metric',
            name='elite_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='high_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='metric',
            name='max_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='medium_threshold_value',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='min_value',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='metric',
            name='source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='recommendation',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='confidence',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='feedback',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='score',
            field=models.IntegerField(choices=[(1, 'Terrible'), (2, 'Bad'), (3, 'Ok'), (4, 'Good'), (5, 'Helpful')], null=True),
        ),
        migrations.AlterField(
            model_name='suggestedrecommendation',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='contact_person',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
