# Generated by Django 4.0 on 2021-12-17 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_metric_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation_matrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('metric1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations1', to='recommend.metric')),
                ('metric2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations2', to='recommend.metric')),
            ],
        ),
    ]
