# Generated by Django 4.0 on 2022-01-01 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0003_alter_recommendation_metric'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='rating',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
