# Generated by Django 4.0 on 2021-12-17 05:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0004_correlation_matrix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Correlation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Dora_kpi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.RenameModel(
            old_name='metric_history',
            new_name='Measurement',
        ),
        migrations.DeleteModel(
            name='Correlation_matrix',
        ),
        migrations.AddField(
            model_name='correlation',
            name='dora_kpi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.dora_kpi'),
        ),
        migrations.AddField(
            model_name='correlation',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='correlations', to='recommend.metric'),
        ),
    ]
